on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun ci

      - name: Build library
        run: bun build:lib

      - name: Build package
        run: bun package

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        # Currently, only npm supports publishing packages with provenance
        # https://docs.npmjs.com/generating-provenance-statements
        run: |
          cd package
          npm publish --provenance --access public
